#!/bin/sh

while getopts ":lr" option; do
    case "${option}" in
        l)
            interaction_title="Liked"
            interaction_tag=like
            ;;
        r)
            interaction_title="RSVP"
            interaction_tag="rsvp"
            ;;
    esac
    shift $((OPTIND-1))
done

if [ ${1+x} ]; then
    target_url=$1
fi

if [ ${target_url+x} ]; then
    target_title=$(curl -s $target_url | grep -o "<title>[^<]*" | tail -c+8)
else
    target_title="Interaction"
fi

# tr replace first w/ second; -c means "complement", -d "delete", -s "squeeze repeats"
# cut trims length; sed command strips trailing whitespace after trimming
slug=$(echo "${interaction_title} ${target_title}" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:] ' | cut -c1-45 | sed -e 's/[[:space:]]*$//' | tr -s " " "-")

isodate=$(date +"%Y-%m-%dT%H:%M:%S%z")
year=$(date +"%Y")
month=$(date +"%m")

# -p: make intermediate directories and don't complain if the full path already exists
mkdir -p pages/interactions/$year/$month

fullpath=pages/interactions/$year/$month/$slug.md

cat >> $fullpath << EOF && codium $fullpath
---
title: "${interaction_title} | ${target_title}"
fedi_url: 
date: $isodate
tags:
  - interaction
  - $interaction_tag
rsvp_value: 
target_url: $target_url
target_title: $target_title
draft: true
---
EOF