#!/bin/sh

if [ ${1+x} ]; then
    name=$1
else
    name="Interaction"
fi

# tr replace first w/ second; -c means "complement", -d "delete", -s "squeeze repeats"
slug=$(echo $name | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:] ' | tr -s " " "-")

isodate=$(date +"%Y-%m-%dT%H:%M:%S%z")
year=$(date +"%Y")
month=$(date +"%m")

# -p: make intermediate directories and don't complain if the full path already exists
mkdir -p pages/posts/$year/$month

fullpath=pages/interactions/$year/$month/$slug.md

cat >> $fullpath << EOF && $fullpath
---
title: $name
canonical_url: https://reillyspitzfaden.com/interactions/$year/$month/$slug/
fedi_url:
date: $isodate
tags:
  - interaction
rsvp_value:
target_url:
target_title:
draft: true
---
EOF