#!/bin/sh

if [ ${1+x} ]; then
    name=$1
else
    # %l is equivalent to %_I (no zero, pad w/ space), hyphen removes padding
    name=$(date +"%b %d, %Y, %-l:%M %p")
fi

# tr replace first w/ second; -c means "complement", -d "delete", -s "squeeze repeats"
slug=$(echo $name | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:] ' | tr -s " " "-")

isodate=$(date +"%Y-%m-%dT%H:%M:%S%z")
year=$(date +"%Y")
month=$(date +"%m")

# -p: make intermediate directories and don't complain if the full path already exists
mkdir -p pages/notes/$year/$month

fullpath=pages/notes/$year/$month/$slug.md

cat >> $fullpath << EOF && codium $fullpath
---
title: $name
fedi_url:
og_image: 
og_image_width: 
og_image_height: 
date: $isodate
tags:
  - note
draft: true
---

<link rel="stylesheet" type="text/css" href="/styles/notes-photos.css">
EOF