#!/bin/sh

isodate=$(date +"%Y-%m-%dT%H:%M:%S%z")
year=$(date +"%Y")
month=$(date +"%m")

while getopts ":d" option; do
    case "${option}" in
        d)
            isodate="$2T00:00:00-0400"
            year=$(echo "${isodate}" | cut -c1-4)
            month=$(echo "${isodate}" | cut -c6-7)
            ;;
    esac
    # remove '-1' because two indices (flag, arg)
    shift $((OPTIND))
done

if [ ${1+x} ]; then
    name=$1
else
    name="Blog Post"
fi

if [ ${2+x} ]; then
    description=$2
else
    description=""
fi

# tr replace first w/ second; -c means "complement", -d "delete", -s "squeeze repeats"
slug=$(echo $name | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:] ' | tr -s " " "-")

# -p: make intermediate directories and don't complain if the full path already exists
mkdir -p pages/posts/$year/$month

fullpath=pages/posts/$year/$month/$slug.md

cat >> $fullpath << EOF
---
title: "$name"
description: $description
fedi_url: 
og_image: 
og_image_width: 
og_image_height: 
date: $isodate
octothorpes:
  - 
tags:
  - post
post_series: 
draft: true
indienews: true
---

<link rel="stylesheet" type="text/css" href="/styles/notes-photos.css">

<link rel="stylesheet" type="text/css" href="/styles/code/prism-perf-custom.css" />
<link rel="stylesheet" type="text/css" href="/styles/code/code-tweaks.css" />
EOF
