#!/usr/bin/env bash

date=$(date +"%Y-%m-%dT%H:%M:%S%z")

location=$(curl -s ipinfo.io | jq -r '.city + ", " + .region')

slug="${date}-status"

fullpath=pages/now/$slug.md

cat >> $fullpath << EOF
---
date: $date
location: $location
tags:
  - status
permalink: false
---
EOF
