#!/bin/sh

while getopts ":hfnrt" option; do
    case "${option}" in
        h)
            folder="."
            ;;
        f)
            folder="favorites"
            ;;
        n)
            folder="notebook"
            ;;
        r)
	    folder="reading"
            ;;
        t)
	    folder="tutorials"
            ;;
    esac
    shift $((OPTIND-1))
done

if [ ${1+x} ]; then
    name=$1
else
    name="Wiki Post"
fi

# tr replace first w/ second; -c means "complement", -d "delete", -s "squeeze repeats"
slug=$(echo $name | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:] ' | tr -s " " "-")

isodate=$(date +"%Y-%m-%dT%H:%M:%S%z")
year=$(date +"%Y")
month=$(date +"%m")

# -p: make intermediate directories and don't complain if the full path already exists
mkdir -p pages/wiki/$folder

fullpath=pages/wiki/$folder/$slug.md

cat >> $fullpath << EOF
---
title: "$name"
description: 
fedi_url: 
og_image: 
og_image_width: 
og_image_height: 
date: git Last Modified
tags:
  - wiki
  - $folder
draft: true
indienews: true
---

<link rel="stylesheet" type="text/css" href="/styles/notes-photos.css">

<link rel="stylesheet" type="text/css" href="/styles/code/prism-perf-custom.css" />
<link rel="stylesheet" type="text/css" href="/styles/code/code-tweaks.css" />
EOF
