name: Trigger Netlify Build
on:
  schedule:
    # Run at 0500 daily
    - cron: '0 5 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: curl -X POST -d '{}' "$BUILD_HOOK"