name: Netlify Build via Webhook
on:
  schedule:
    # Run at 0500 daily
    - cron: '42 * * * *'

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    env:
      BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
    steps:
    - name: Curl request
      run: curl -X POST -d {} "$BUILD_HOOK"