name: Netlify Deploy

on:
  schedule:
    - cron: "49 * * * *"

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    env:
      BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
    steps:
    - name: Curl request
      run: curl -X POST -d {} "$BUILD_HOOK"