name: Netlify Build via Webhook
on:
  schedule:
    # Run at 0500 daily
    - cron: '35 * * * *'

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
    - name: Curl request
      run: curl -X POST -d {} https://api.netlify.com/build_hooks/67a53bc75c61637e30fc412e