name: Netlify Deploy via Webhook

on:
  schedule:
    - cron: "43 1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    env:
      BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
    steps:
      - name: Curl request
        run: curl -X POST -d {} "$BUILD_HOOK"